name: Autotag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push tag
        run: |
          if git describe --exact-match HEAD 2>/dev/null; then
            echo "Commit already tagged, skipping"
            exit 0
          fi
          LAST_TAGGED_COMMIT=$(git rev-list --tags --max-count=1)
          if [ -z "$LAST_TAGGED_COMMIT" ]; then
            TAG="1.0.0"
          else
            TAG=$(git describe --tags "$LAST_TAGGED_COMMIT")
            TAG=${TAG%.*}.$((${TAG##*.} + 1))
          fi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "$TAG" -m "Auto-tagging the current commit"
          git push --tags
